### ISSUE TITLE
运行app.py以后，我遇到了以下错误，想请教一下是不是我缺失了步骤，谢谢

### ISSUE THREAD

**Issue by Dxqre** [YangBin1729/textSum#1]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Code\\textSum\\saved\\word2vec/wiki_corpus_above200.model'

**Comment by YangBin1729** [comment]
那是因为没有模型文件，我已经上传了百度网盘地址



发自我的&nbsp;iPad


------------------ 原始邮件 ------------------
发件人: Dxqre <notifications@github.com&gt;
发送时间: 2020年6月10日 22:06
收件人: YangBin1729/textSum <textSum@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[YangBin1729/textSum] 运行app.py以后，我遇到了以下错误，想请教一下是不是我缺失了步骤，谢谢 (#1)





 
FileNotFoundError: [Errno 2] No such file or directory: 'D:\Code\textSum\saved\word2vec/wiki_corpus_above200.model'

**Comment by tiexueYL** [comment]
> 那是因为没有模型文件，我已经上传了百度网盘地址 发自我的&nbsp;iPad
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Dxqre <notifications@github.com&gt; 发送时间: 2020年6月10日 22:06 收件人: YangBin1729/textSum <textSum@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[YangBin1729/textSum] 运行app.py以后，我遇到了以下错误，想请教一下是不是我缺失了步骤，谢谢 (#1) FileNotFoundError: [Errno 2] No such file or directory: 'D:\Code\textSum\saved\word2vec/wiki_corpus_above200.model' — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
大佬打扰您了，请问运行app.py以后一直卡在 Running on http://192.168.122.217:8000/ (Press CTRL+C to quit)这个状态不动，用一个2080TI去跑大概多久可以结束呢？
